
default_connection_name = "myconnection"
[connections]
[connections.myconnection]
user = ""

#default_connection_name = "my_test_connection" 
#[connections]
#[connections.my_test_connection]
#account = "eyyzdoj-sg96461"
#user = "pradeep"
#password = "afd$"
#database = "DEMO_DB"
#schema = "PUBLIC"
