name: Deploy AWS Glue Job

on:
  push:
    branches:
      - dev  # Trigger the action on push to the main branch, adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Step 3: Install dependencies (if needed)
    - name: Install dependencies
      run: |
        pip install awscli

    # Step 4: Deploy CloudFormation stack (Create or Update)
    - name: Deploy CloudFormation stack
      run: |
        TEMPLATE_FILE="./template.yml"
        aws cloudformation create-stack \
          --stack-name github-action-aws-stack \
          --template-body file://$TEMPLATE_FILE \
          --capabilities CAPABILITY_IAM \
          --region ${{ secrets.AWS_DEFAULT_REGION }}
          
        aws s3 cp ./api_to_s3/fetch_from_api_to_s3.py s3://mys3bucket068/scripts/fetch_from_api_to_s3.py

    # Optional: Verify deployment
    - name: Verify deployment
      run: |
        aws cloudformation describe-stacks --stack-name glue-job-stack
